---
sudo: required
dist: trusty

language: python
python: "2.7"
services:
- docker

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
- PROJECT_VERSION=Windows ANSIBLE_VERSION=2.4.2.0
- PROJECT_VERSION=Darwin ANSIBLE_VERSION=2.4.2.0
- PROJECT_VERSION=Linux ANSIBLE_VERSION=2.4.2.0
- PROJECT_VERSION=Windows ANSIBLE_VERSION=2.2.0

- PROJECT_VERSION=Darwin ANSIBLE_VERSION=2.2.0
- PROJECT_VERSION=Linux ANSIBLE_VERSION=2.2.0
branches:
  only:
  - master

before_install:
- sudo apt-get update -qq

install:
  # Install Ansible.
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
- pip install molecule
- pip install docker-py

before_script:
- mv $TRAVIS_BUILD_DIR ../menedev.docker-compose
- cd ../menedev.docker-compose
- export TRAVIS_BUILD_DIR=`pwd`

script:
- DOCKER_COMPOSE_VERSION=$PROJECT_VERSION DOCKER_COMPOSE_VERSION_EXPECT=$EXPECT molecule
  --debug test
  # - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  # # Check the role/playbook's syntax.
  # - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # # Run the role/playbook with ansible-playbook.
  # - ansible-playbook -i tests/inventory tests/test.yml -vvvv --connection=local --skip-tags update,copy_host_ssh_id

  # # check is the user is created or not
  # - docker-compose version | grep "docker-compose version" | grep "$DOCKER_COMPOSE_VERSION"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
